### ISSUE TITLE
Chinese characters garbled

### ISSUE THREAD

**Issue by MatthK** [ich777/docker-firefox#2]
I just managed to get this running on a Raspberry Pi 4B. Although it's slow, it is working.

But when I try to go to a website with Chinese characters, it displays them garbled. Is there a setting that I can define to get this show the Chinese characters as well?

And I was wondering how I can get this to work behind a Reverse Proxy. I tried my normal setup, but I keep getting an error message saying it "failed to connect to server".

**Comment by ich777** [comment]
> But when I try to go to a website with Chinese characters, it displays them garbled. Is there a setting that I can define to get this show the Chinese characters as well?

I think a font is missing can you open up a terminal from the container and run:
`apt-get update && apt-get -y install fonts-noto-cjk`
After you did that restart the container and see if the issue is resolved and please report back.

> And I was wondering how I can get this to work behind a Reverse Proxy. I tried my normal setup, but I keep getting an error message saying it "failed to connect to server".

Sure thing here is the config I use with nginx and Authelia (if you don't use Authelia you have to remove those lines):
```
server {
	listen 443 ssl;

	include /config/nginx/ssl.conf;
	include /config/nginx/error.conf;
	include /config/nginx/authelia-server.conf;

	server_name subdomain.example.org;

	location /websockify {
		include /config/nginx/authelia-location.conf;
		proxy_http_version 1.1;
		proxy_pass http://firefox:8080/;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";

		# VNC connection timeout
		proxy_read_timeout 61s;

		# Disable cache
		proxy_buffering off;
	}
		location / {
		rewrite ^/$ https://yoursubdomain.example.org/vnc.html?autoconnect=true redirect;
		include /config/nginx/authelia-location.conf;
		proxy_redirect     off;
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_pass http://firefox:8080/;
	}
}
```

Be sure to change the values at `proxy_pass` and `yoursubdomain.example.org` to match your config, also don't forget to remove the lines `include /config/nginx/authelia-location.conf;` if you don't use Authelia.

**Comment by MatthK** [comment]
Ok, I managed to get the Reverse Proxy working. 

I had to add this to the config file and restart nginx.

```
    location /websockify {
          proxy_http_version 1.1;
          proxy_pass http://vnc_proxy/;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # VNC connection timeout
          proxy_read_timeout 61s;

          # Disable cache
          proxy_buffering off;
    }
```

**Comment by ich777** [comment]
@MatthK have you also tried if the command from above and a restart solves the Chinese character issue? If it solves the issue I can push a fix.

**Comment by MatthK** [comment]
Our replies have just crossed each other. I googled for the Reverse Proxy answer and found a solution, and posted it here, And only after that saw your reply.

I have taken over your proxy solution, and also the installation of the fonts worked flawlessly. Thank you very much. 

Extremely fast response, I'm highly impressed.

**Comment by ich777** [comment]
> Although it's slow, it is working.

Try to run it from a SSD or from a spinning HDD connected via USB3.0 then it should be a lot faster, I also recommend using the ARM64 bit version from the OS that you are running on the Pi itself, I was very impressed by Armbian.

> I have taken over your proxy solution, and also the installation of the fonts worked flawlessly. Thank you very much.

Pushed already a update from the container to fix the garbled characters, pull a update and everything should work now fine.

**Comment by MatthK** [comment]
I might move it to a faster machine. The Raspberry is more of a testbed to check things out. And the Raspi is running 64bit Ubuntu 20.04.3 LTS
